apiVersion: v2
name: bytewax
description: A Helm chart for Bytewax
type: application
version: 0.8.1
appVersion: "0.19.0"
icon: https://bytewax.io/assets/img/favicon.png
dependencies:
- condition: opentelemetry-collector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.36.*
- condition: jaeger.enabled
  name: jaeger
  repository: https://jaegertracing.github.io/helm-charts
  version: 0.62.*
- condition: kubePrometheusStack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 56.2.*